services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: yaShop
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: yaShop
    ports:
      - "5433:5432"
    volumes:
      - .pg-oper-data:/var/lib/postgresql/data
    networks:
      postgres_network:

networks:
  postgres_network: